### ISSUE TITLE
initial setup for B2B

### ISSUE THREAD

**Issue by rjvillanueva89** [UpBrewTech/project-leasa#11]
to include
- auth/login - using credentials provider
- auth/registration - name, email and password
- dashboard page

adding packages to B2B:
- react-hook-form 
- yup 
- @hookform/resolvers

with command:
```bash
pnpm add react-hook-form yup @hookform/resolvers --filter b2b
```

hasura docker notes:
- solves localhost and network request CORS Issue and "unauthorized role"
```yaml
# file: docker-compose.yaml
services:
  ...
  graphql-engine:
    ...
    environment:
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: PUBLIC
```
source: [hasura documentation](https://hasura.io/docs/latest/deployment/graphql-engine-flags/config-examples/#configure-cors)

- pointed to hasura docker
```Shell
# .env.samlpe
NEXT_PUBLIC_HASURA_GRAPHQL_API = http://localhost:8080/v1/graphql
NEXT_PUBLIC_HASURA_GRAPHQL_API_WS = ws://localhost:8080/v1/graphql
```
